// Generated by Framer (9e04080)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "pv1v45", mediaQuery: "(min-width: 1200px)"}, {hash: "df1bw1", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "tic4ml", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-BO8GW", title: siteMetadata(params, activeLocale).title || "404", viewport: "width=device-width"}
}

export const metadataVersion = 1