// Generated by Framer (b4533c2)

import siteMetadata from "../siteMetadata/siteMetadata";

const valuesByLocaleId = {}

function getLocalizedValue (key, locale){while (locale) {const values = valuesByLocaleId[locale.id]
if (values) {const value = values[key]
if (value) return value}
locale = locale.fallback}}

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "mswhu", mediaQuery: "(min-width: 1200px)"}, {hash: "nr1sbv", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "5hob55", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {oUuXX1S4u: "our-team"}, robots: "max-image-preview:large", serializationId: "framer-f4wX6", title: siteMetadata(params, activeLocale).title || "About", viewport: "width=device-width"}
}

export const metadataVersion = 1