// Generated by Framer (b4533c2)

import siteMetadata from "../siteMetadata/siteMetadata";

const valuesByLocaleId = {}

function getLocalizedValue (key, locale){while (locale) {const values = valuesByLocaleId[locale.id]
if (values) {const value = values[key]
if (value) return value}
locale = locale.fallback}}

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "3gtb4f", mediaQuery: "(min-width: 1200px)"}, {hash: "1yu2izs", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "1k28k65", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {F4t3FjAI9: "luxury-facials", K7gL4kdIl: "hot-stone-therapy", ng4CW174y: "aromatherapy-rituals", NkPdjp_X1: "deep-tissue-massage", Y7AhEhY5x: "full-body-detox-wrap", zn3Lcg5LF: "spa-manicure-pedicure"}, robots: "max-image-preview:large", serializationId: "framer-gRsVU", title: siteMetadata(params, activeLocale).title || "Services", viewport: "width=device-width"}
}

export const metadataVersion = 1