[build]
  # No build command needed for static site
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Clean URL redirects - Hide Framer references
[[redirects]]
  from = "/"
  to = "/sk/"
  status = 301

[[redirects]]
  from = "/sk"
  to = "/sk/"
  status = 301

[[redirects]]
  from = "/sk/*"
  to = "/extraordinary-acknowledge-696942.framer.app/sk/:splat"
  status = 200

# Handle SPA routing fallback
[[redirects]]
  from = "/*"
  to = "/extraordinary-acknowledge-696942.framer.app/sk/index.html"
  status = 200
