// Generated by Framer (f030ee3)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "tovxtx"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-QzvFo", title: siteMetadata(params, activeLocale).title || "Blog", viewport: "width=1200"}
}

export const metadataVersion = 1