// Generated by Framer (b4533c2)
import {
    addPropertyControls as e,
    ControlType as l,
    QueryCache as r,
    QueryEngine as t
} from "framer";
import {
    DatabaseCollection as m,
    DatabaseDictionaryIndex as o
} from "./F_VpTXLBp-0.js";
import {
    resolveRichText as a
} from "./F_VpTXLBp-1.js";
import {
    resolveRichTextSk as i
} from "./F_VpTXLBp-3.js";
let n = {
        EzWVGX8FU: {
            isNullable: !0,
            type: l.RichText
        },
        id: {
            isNullable: !1,
            type: l.String
        },
        jus9m0OzH: {
            isNullable: !0,
            type: l.String
        },
        nextItemId: {
            isNullable: !0,
            type: l.String
        },
        previousItemId: {
            isNullable: !0,
            type: l.String
        },
        tbt2toPCY: {
            isNullable: !0,
            type: l.Link
        },
        uiKOgnPIs: {
            isNullable: !0,
            type: l.String
        },
        vco5XdhS_: {
            isNullable: !0,
            type: l.String
        },
        XiO2mbSnW: {
            isNullable: !0,
            type: l.String
        },
        yVIu_r2OD: {
            isNullable: !0,
            type: l.String
        }
    },
    c = ["id", "EzWVGX8FU"],
    s = {
        type: 1
    },
    p = ["previousItemId", "EzWVGX8FU"],
    u = ["nextItemId", "EzWVGX8FU"],
    f = ["id", "jus9m0OzH"],
    d = ["jus9m0OzH", "id"],
    w = ["XiO2mbSnW", "EzWVGX8FU"],
    h = {
        type: 0
    },
    L = ["jus9m0OzH", "EzWVGX8FU"],
    V = ["vco5XdhS_", "EzWVGX8FU"],
    X = ["uiKOgnPIs", "EzWVGX8FU"],
    T = ["tbt2toPCY", "EzWVGX8FU"],
    g = ["yVIu_r2OD", "EzWVGX8FU"],
    S = ["EzWVGX8FU", "EzWVGX8FU"],
    y = [],
    R = e => {
        let l = y[e];
        if (l) return l().then(e => e.default);
    },
    F = new t,
    U = new r(F),
    x = {
        collectionByLocaleId: {
            default: new m({
                chunks: [new URL("./F_VpTXLBp-chunk-default-0.framercms",
                    import.meta.url).href.replace("/modules/", "/cms/")],
                indexes: [new o({
                    collation: s,
                    collectionSchema: n,
                    fieldNames: c,
                    range: {
                        from: 0,
                        to: 1658
                    },
                    url: new URL("./F_VpTXLBp-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new o({
                    collation: s,
                    collectionSchema: n,
                    fieldNames: p,
                    range: {
                        from: 1658,
                        to: 3315
                    },
                    url: new URL("./F_VpTXLBp-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new o({
                    collation: s,
                    collectionSchema: n,
                    fieldNames: u,
                    range: {
                        from: 3315,
                        to: 4968
                    },
                    url: new URL("./F_VpTXLBp-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new o({
                    collation: s,
                    collectionSchema: n,
                    fieldNames: f,
                    range: {
                        from: 4968,
                        to: 7985
                    },
                    url: new URL("./F_VpTXLBp-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new o({
                    collation: s,
                    collectionSchema: n,
                    fieldNames: d,
                    range: {
                        from: 7985,
                        to: 11002
                    },
                    url: new URL("./F_VpTXLBp-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new o({
                    collation: h,
                    collectionSchema: n,
                    fieldNames: w,
                    range: {
                        from: 11002,
                        to: 13630
                    },
                    url: new URL("./F_VpTXLBp-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new o({
                    collation: h,
                    collectionSchema: n,
                    fieldNames: L,
                    range: {
                        from: 13630,
                        to: 16222
                    },
                    url: new URL("./F_VpTXLBp-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new o({
                    collation: h,
                    collectionSchema: n,
                    fieldNames: V,
                    range: {
                        from: 16222,
                        to: 17725
                    },
                    url: new URL("./F_VpTXLBp-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new o({
                    collation: h,
                    collectionSchema: n,
                    fieldNames: X,
                    range: {
                        from: 17725,
                        to: 19098
                    },
                    url: new URL("./F_VpTXLBp-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new o({
                    collation: h,
                    collectionSchema: n,
                    fieldNames: T,
                    range: {
                        from: 19098,
                        to: 24759
                    },
                    url: new URL("./F_VpTXLBp-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new o({
                    collation: h,
                    collectionSchema: n,
                    fieldNames: g,
                    range: {
                        from: 24759,
                        to: 26424
                    },
                    url: new URL("./F_VpTXLBp-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new o({
                    collation: h,
                    collectionSchema: n,
                    fieldNames: S,
                    range: {
                        from: 26424,
                        to: 27657
                    },
                    url: new URL("./F_VpTXLBp-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                })],
                resolveRichText: a,
                resolveVectorSetItem: R,
                schema: n
            }),
            GowRT4MZZ: new m({
                chunks: [new URL("./F_VpTXLBp-chunk-GowRT4MZZ-0.framercms",
                    import.meta.url).href.replace("/modules/", "/cms/")],
                indexes: [new o({
                    collation: s,
                    collectionSchema: n,
                    fieldNames: c,
                    range: {
                        from: 0,
                        to: 1658
                    },
                    url: new URL("./F_VpTXLBp-indexes-GowRT4MZZ-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new o({
                    collation: s,
                    collectionSchema: n,
                    fieldNames: p,
                    range: {
                        from: 1658,
                        to: 3315
                    },
                    url: new URL("./F_VpTXLBp-indexes-GowRT4MZZ-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new o({
                    collation: s,
                    collectionSchema: n,
                    fieldNames: u,
                    range: {
                        from: 3315,
                        to: 4968
                    },
                    url: new URL("./F_VpTXLBp-indexes-GowRT4MZZ-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new o({
                    collation: s,
                    collectionSchema: n,
                    fieldNames: f,
                    range: {
                        from: 4968,
                        to: 7985
                    },
                    url: new URL("./F_VpTXLBp-indexes-GowRT4MZZ-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new o({
                    collation: s,
                    collectionSchema: n,
                    fieldNames: d,
                    range: {
                        from: 7985,
                        to: 11002
                    },
                    url: new URL("./F_VpTXLBp-indexes-GowRT4MZZ-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new o({
                    collation: h,
                    collectionSchema: n,
                    fieldNames: w,
                    range: {
                        from: 11002,
                        to: 14198
                    },
                    url: new URL("./F_VpTXLBp-indexes-GowRT4MZZ-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new o({
                    collation: h,
                    collectionSchema: n,
                    fieldNames: L,
                    range: {
                        from: 14198,
                        to: 16790
                    },
                    url: new URL("./F_VpTXLBp-indexes-GowRT4MZZ-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new o({
                    collation: h,
                    collectionSchema: n,
                    fieldNames: V,
                    range: {
                        from: 16790,
                        to: 18368
                    },
                    url: new URL("./F_VpTXLBp-indexes-GowRT4MZZ-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new o({
                    collation: h,
                    collectionSchema: n,
                    fieldNames: X,
                    range: {
                        from: 18368,
                        to: 19905
                    },
                    url: new URL("./F_VpTXLBp-indexes-GowRT4MZZ-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new o({
                    collation: h,
                    collectionSchema: n,
                    fieldNames: T,
                    range: {
                        from: 19905,
                        to: 25566
                    },
                    url: new URL("./F_VpTXLBp-indexes-GowRT4MZZ-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new o({
                    collation: h,
                    collectionSchema: n,
                    fieldNames: g,
                    range: {
                        from: 25566,
                        to: 27231
                    },
                    url: new URL("./F_VpTXLBp-indexes-GowRT4MZZ-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new o({
                    collation: h,
                    collectionSchema: n,
                    fieldNames: S,
                    range: {
                        from: 27231,
                        to: 28464
                    },
                    url: new URL("./F_VpTXLBp-indexes-GowRT4MZZ-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                })],
                resolveRichText: i,
                resolveVectorSetItem: R,
                schema: n
            })
        },
        displayName: "Services"
    };
export default x;
e(x, {
    XiO2mbSnW: {
        defaultValue: "",
        title: "Title",
        type: l.String
    },
    jus9m0OzH: {
        title: "Slug",
        type: l.String
    },
    vco5XdhS_: {
        defaultValue: "",
        title: "Duration",
        type: l.String
    },
    uiKOgnPIs: {
        defaultValue: "",
        title: "Price",
        type: l.String
    },
    tbt2toPCY: {
        title: "Service Link",
        type: l.Link
    },
    yVIu_r2OD: {
        dataIdentifier: "local-module:collection/xqQPQSXue:default",
        title: "Category of Services",
        type: l.CollectionReference
    },
    EzWVGX8FU: {
        defaultValue: "",
        title: "Description",
        type: l.RichText
    },
    previousItemId: {
        dataIdentifier: "local-module:collection/F_VpTXLBp:default",
        title: "Previous",
        type: l.CollectionReference
    },
    nextItemId: {
        dataIdentifier: "local-module:collection/F_VpTXLBp:default",
        title: "Next",
        type: l.CollectionReference
    }
});
export const enumToDisplayNameFunctions = {};
export const utils = {
    async getSlugByRecordId(e, l) {
        let [r] = await U.get({
            from: {
                data: x,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "jus9m0OzH",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "id",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, l).readAsync();
        return r ? .jus9m0OzH;
    },
    async getRecordIdBySlug(e, l) {
        let [r] = await U.get({
            from: {
                data: x,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "id",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "jus9m0OzH",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, l).readAsync();
        return r ? .id;
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "data",
            "name": "data",
            "annotations": {
                "framerCollectionId": "F_VpTXLBp",
                "framerData": "",
                "framerColorSyntax": "false",
                "framerAutoSizeImages": "true",
                "framerSlug": "jus9m0OzH",
                "framerCollectionUtils": "1",
                "framerEnumToDisplayNameUtils": "2",
                "framerRecordIdKey": "id",
                "framerContractVersion": "1"
            }
        },
        "enumToDisplayNameFunctions": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "utils": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}