// Generated by Framer (9e04080)

import siteMetadata from "../siteMetadata/siteMetadata";

const toString = (value) => {
    return typeof value === "string" ? value : String(value);
};


export default function metadata(params, activeLocale) {
const rwyNkDp7y = params?.rwyNkDp7y
return {breakpoints: [{hash: "18a9l67", mediaQuery: "(min-width: 1200px)"}, {hash: "r2cca4", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "13x1f7e", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-Y9JmG", title: `${rwyNkDp7y !== undefined ? toString(rwyNkDp7y) : "{{rwyNkDp7y}}"} - Vistiq`, viewport: "width=device-width"}
}

export const metadataVersion = 1