// Generated by Framer (b4533c2)

import siteMetadata from "../siteMetadata/siteMetadata";

const valuesByLocaleId = {}

function getLocalizedValue (key, locale){while (locale) {const values = valuesByLocaleId[locale.id]
if (values) {const value = values[key]
if (value) return value}
locale = locale.fallback}}

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "72rtr7", mediaQuery: "(min-width: 1200px)"}, {hash: "u9uq27", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "1y2fjk5", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {NOs7TsB48: "about-section-00", RVK_DnsUd: "about-section-01", SKnjuObFJ: "testimonials-scroll-section", TBzkbe1fV: "about-section-02"}, robots: "max-image-preview:large", serializationId: "framer-WKeCp", title: siteMetadata(params, activeLocale).title || "Home", viewport: "width=device-width"}
}

export const metadataVersion = 1