// Generated by Framer (b4533c2)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    cx,
    Link,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const enabledGestures = {
    Tl53BCOS8: {
        hover: true
    }
};
const serializationHash = "framer-5CzcM";
const variantClassNames = {
    Tl53BCOS8: "framer-v-6f9jng"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    damping: 60,
    delay: 0,
    mass: 1,
    stiffness: 500,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "Tl53BCOS8",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: "https://framer.link/WozTloh",
                    motionChild: true,
                    nodeId: "Tl53BCOS8",
                    openInNewTab: true,
                    scopeId: "BQ0ALqHbh",
                    children: /*#__PURE__*/ _jsxs(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-6f9jng",className,classNames)} framer-kri108`,
                        "data-framer-name": "Variant 1",
                        layoutDependency: layoutDependency,
                        layoutId: "Tl53BCOS8",
                        ref: refBinding,
                        style: {
                            borderBottomLeftRadius: 10,
                            borderBottomRightRadius: 10,
                            borderTopLeftRadius: 10,
                            borderTopRightRadius: 10,
                            boxShadow: "0px 2px 4px 0px rgba(0, 0, 0, 0.1)",
                            ...style
                        },
                        ...addPropertyOverrides({
                            "Tl53BCOS8-hover": {
                                "data-framer-name": undefined
                            }
                        }, baseVariant, gestureVariant),
                        children: [ /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-1hgspza",
                            "data-framer-name": "Blur",
                            layoutDependency: layoutDependency,
                            layoutId: "eTp3eGbLx",
                            style: {
                                backgroundColor: "rgba(255, 255, 255, 0.5)",
                                borderBottomLeftRadius: 10,
                                borderBottomRightRadius: 10,
                                borderTopLeftRadius: 10,
                                borderTopRightRadius: 10,
                                filter: "blur(5px)",
                                opacity: 0,
                                WebkitFilter: "blur(5px)"
                            }
                        }), /*#__PURE__*/ _jsx(motion.button, {
                            className: "framer-74fvzx",
                            "data-reset": "button",
                            layoutDependency: layoutDependency,
                            layoutId: "Uq3Qq2r16",
                            style: {
                                backgroundColor: "var(--token-922bf7e2-6566-450d-a5db-d314f15d527e, rgb(51, 51, 51))",
                                borderBottomLeftRadius: 10,
                                borderBottomRightRadius: 10,
                                borderTopLeftRadius: 10,
                                borderTopRightRadius: 10
                            },
                            variants: {
                                "Tl53BCOS8-hover": {
                                    backgroundColor: "var(--token-9ac73791-4104-4253-8947-ec829a0f0956, rgb(102, 102, 102))"
                                }
                            },
                            children: /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        style: {
                                            "--font-selector": "SW50ZXItU2VtaUJvbGQ=",
                                            "--framer-font-family": '"Inter", "Inter Placeholder", sans-serif',
                                            "--framer-font-size": "14px",
                                            "--framer-font-weight": "600",
                                            "--framer-text-color": "var(--extracted-r6o4lv, var(--token-5df573a8-5c6e-4a5b-bca6-248c4c391d54, rgb(255, 255, 255)))"
                                        },
                                        children: "Remix Template"
                                    })
                                }),
                                className: "framer-ramt4d",
                                fonts: ["Inter-SemiBold"],
                                layoutDependency: layoutDependency,
                                layoutId: "IfEKV3Dnz",
                                style: {
                                    "--extracted-r6o4lv": "var(--token-5df573a8-5c6e-4a5b-bca6-248c4c391d54, rgb(255, 255, 255))",
                                    "--framer-link-text-color": "rgb(0, 153, 255)",
                                    "--framer-link-text-decoration": "underline"
                                },
                                verticalAlignment: "top",
                                withExternalLayout: true
                            })
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-5CzcM.framer-kri108, .framer-5CzcM .framer-kri108 { display: block; }", ".framer-5CzcM.framer-6f9jng { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 36px; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: 142px; }", ".framer-5CzcM .framer-1hgspza { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-override, transform); z-index: 1; }", ".framer-5CzcM .framer-74fvzx { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 36px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 142px; z-index: 1; }", ".framer-5CzcM .framer-ramt4d { flex: none; height: auto; position: relative; white-space: pre; width: auto; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 36
 * @framerIntrinsicWidth 142
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"OkO3vvm5Z":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerBQ0ALqHbh = withCSS(Component, css, "framer-5CzcM");
export default FramerBQ0ALqHbh;
FramerBQ0ALqHbh.displayName = "Get Template Button";
FramerBQ0ALqHbh.defaultProps = {
    height: 36,
    width: 142
};
addFonts(FramerBQ0ALqHbh, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2",
        weight: "600"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2",
        weight: "600"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2",
        weight: "600"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/lEJLP4R0yuCaMCjSXYHtJw72M.woff2",
        weight: "600"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2",
        weight: "600"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/1ZFS7N918ojhhd0nQWdj3jz4w.woff2",
        weight: "600"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2",
        weight: "600"
    }]
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerBQ0ALqHbh",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerColorSyntax": "true",
                "framerComponentViewportWidth": "true",
                "framerAutoSizeImages": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"OkO3vvm5Z\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerIntrinsicHeight": "36",
                "framerDisplayContentsDiv": "false",
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "142"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./BQ0ALqHbh.map