// Generated by Framer (0c5492c)
import {
    fontStore
} from "framer";
fontStore.loadFonts(["GF;Kumbh Sans-500", "GF;Kumbh Sans-700"]);
export const fonts = [{
    explicitInter: true,
    fonts: [{
        family: "Kumbh Sans",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/kumbhsans/v22/c4mP1n92AsfhuCq6tVsaoIx1LQICk0boNoq0SjlDfnzKo-bF3mdQo5YA9LTuUkqaLg.woff2",
        weight: "500"
    }, {
        family: "Kumbh Sans",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/kumbhsans/v22/c4mP1n92AsfhuCq6tVsaoIx1LQICk0boNoq0SjlDfnzKo-bF3mdQdpEA9LTuUkqaLg.woff2",
        weight: "700"
    }]
}];
export const css = ['.framer-Ffuj3 .framer-styles-preset-1tbhouf:not(.rich-text-wrapper), .framer-Ffuj3 .framer-styles-preset-1tbhouf.rich-text-wrapper p { --framer-font-family: "Kumbh Sans", "Kumbh Sans Placeholder", sans-serif; --framer-font-family-bold: "Kumbh Sans", "Kumbh Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-922bf7e2-6566-450d-a5db-d314f15d527e, #333333); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: inherit; }'];
export const className = "framer-Ffuj3";
export const __FramerMetadata__ = {
    "exports": {
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}