// Generated by Framer (ab692b1)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import {
    Icon as Phosphor
} from "https://framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/p8dptk4UIND8hbFWz9V7/Phosphor.js";
const PhosphorFonts = getFonts(Phosphor);
const serializationHash = "framer-MMwxq";
const variantClassNames = {
    A0ytmC0JB: "framer-v-1789rqi"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    color,
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        y7Kysh53S: color ? ? props.y7Kysh53S ? ? "var(--token-5df573a8-5c6e-4a5b-bca6-248c4c391d54, rgb(255, 255, 255))"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        y7Kysh53S,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "A0ytmC0JB",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1789rqi", className, classNames),
                    "data-framer-name": "Variant 1",
                    layoutDependency: layoutDependency,
                    layoutId: "A0ytmC0JB",
                    ref: refBinding,
                    style: { ...style
                    },
                    children: [ /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-w0t6db-container",
                            isAuthoredByUser: true,
                            isModuleExternal: true,
                            layoutDependency: layoutDependency,
                            layoutId: "RGXxLEgy7-container",
                            nodeId: "RGXxLEgy7",
                            rendersWithMotion: true,
                            scopeId: "QJdumGSLZ",
                            children: /*#__PURE__*/ _jsx(Phosphor, {
                                color: y7Kysh53S,
                                height: "100%",
                                iconSearch: "House",
                                iconSelection: "Star",
                                id: "RGXxLEgy7",
                                layoutId: "RGXxLEgy7",
                                mirrored: false,
                                selectByList: true,
                                style: {
                                    height: "100%",
                                    width: "100%"
                                },
                                weight: "fill",
                                width: "100%"
                            })
                        })
                    }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-esy78l-container",
                            isAuthoredByUser: true,
                            isModuleExternal: true,
                            layoutDependency: layoutDependency,
                            layoutId: "UhBbXhmT2-container",
                            nodeId: "UhBbXhmT2",
                            rendersWithMotion: true,
                            scopeId: "QJdumGSLZ",
                            children: /*#__PURE__*/ _jsx(Phosphor, {
                                color: y7Kysh53S,
                                height: "100%",
                                iconSearch: "House",
                                iconSelection: "Star",
                                id: "UhBbXhmT2",
                                layoutId: "UhBbXhmT2",
                                mirrored: false,
                                selectByList: true,
                                style: {
                                    height: "100%",
                                    width: "100%"
                                },
                                weight: "fill",
                                width: "100%"
                            })
                        })
                    }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-v2nqws-container",
                            isAuthoredByUser: true,
                            isModuleExternal: true,
                            layoutDependency: layoutDependency,
                            layoutId: "ZV_0ZB0ZM-container",
                            nodeId: "ZV_0ZB0ZM",
                            rendersWithMotion: true,
                            scopeId: "QJdumGSLZ",
                            children: /*#__PURE__*/ _jsx(Phosphor, {
                                color: y7Kysh53S,
                                height: "100%",
                                iconSearch: "House",
                                iconSelection: "Star",
                                id: "ZV_0ZB0ZM",
                                layoutId: "ZV_0ZB0ZM",
                                mirrored: false,
                                selectByList: true,
                                style: {
                                    height: "100%",
                                    width: "100%"
                                },
                                weight: "fill",
                                width: "100%"
                            })
                        })
                    }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-r7eh8-container",
                            isAuthoredByUser: true,
                            isModuleExternal: true,
                            layoutDependency: layoutDependency,
                            layoutId: "W4er2VcN4-container",
                            nodeId: "W4er2VcN4",
                            rendersWithMotion: true,
                            scopeId: "QJdumGSLZ",
                            children: /*#__PURE__*/ _jsx(Phosphor, {
                                color: y7Kysh53S,
                                height: "100%",
                                iconSearch: "House",
                                iconSelection: "Star",
                                id: "W4er2VcN4",
                                layoutId: "W4er2VcN4",
                                mirrored: false,
                                selectByList: true,
                                style: {
                                    height: "100%",
                                    width: "100%"
                                },
                                weight: "fill",
                                width: "100%"
                            })
                        })
                    }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-7ox6x7-container",
                            isAuthoredByUser: true,
                            isModuleExternal: true,
                            layoutDependency: layoutDependency,
                            layoutId: "EP8ljJXmw-container",
                            nodeId: "EP8ljJXmw",
                            rendersWithMotion: true,
                            scopeId: "QJdumGSLZ",
                            children: /*#__PURE__*/ _jsx(Phosphor, {
                                color: y7Kysh53S,
                                height: "100%",
                                iconSearch: "House",
                                iconSelection: "Star",
                                id: "EP8ljJXmw",
                                layoutId: "EP8ljJXmw",
                                mirrored: false,
                                selectByList: true,
                                style: {
                                    height: "100%",
                                    width: "100%"
                                },
                                weight: "fill",
                                width: "100%"
                            })
                        })
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-MMwxq.framer-lo1go0, .framer-MMwxq .framer-lo1go0 { display: block; }", ".framer-MMwxq.framer-1789rqi { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }", ".framer-MMwxq .framer-w0t6db-container, .framer-MMwxq .framer-esy78l-container, .framer-MMwxq .framer-v2nqws-container, .framer-MMwxq .framer-r7eh8-container, .framer-MMwxq .framer-7ox6x7-container { flex: none; height: 12px; position: relative; width: 12px; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-MMwxq.framer-1789rqi { gap: 0px; } .framer-MMwxq.framer-1789rqi > * { margin: 0px; margin-left: calc(4px / 2); margin-right: calc(4px / 2); } .framer-MMwxq.framer-1789rqi > :first-child { margin-left: 0px; } .framer-MMwxq.framer-1789rqi > :last-child { margin-right: 0px; } }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 12
 * @framerIntrinsicWidth 76
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]}}}
 * @framerVariables {"y7Kysh53S":"color"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */
const FramerQJdumGSLZ = withCSS(Component, css, "framer-MMwxq");
export default FramerQJdumGSLZ;
FramerQJdumGSLZ.displayName = "5-stars";
FramerQJdumGSLZ.defaultProps = {
    height: 12,
    width: 76
};
addPropertyControls(FramerQJdumGSLZ, {
    y7Kysh53S: {
        defaultValue: 'var(--token-5df573a8-5c6e-4a5b-bca6-248c4c391d54, rgb(255, 255, 255)) /* {"name":"Light 100"} */',
        title: "Color",
        type: ControlType.Color
    }
});
addFonts(FramerQJdumGSLZ, [{
    explicitInter: true,
    fonts: []
}, ...PhosphorFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerQJdumGSLZ",
            "slots": [],
            "annotations": {
                "framerVariables": "{\"y7Kysh53S\":\"color\"}",
                "framerComponentViewportWidth": "true",
                "framerDisplayContentsDiv": "false",
                "framerContractVersion": "1",
                "framerIntrinsicHeight": "12",
                "framerIntrinsicWidth": "76",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerImmutableVariables": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./QJdumGSLZ.map