// Generated by Framer (9e04080)
import {
    addPropertyControls as e,
    ControlType as t,
    QueryCache as l,
    QueryEngine as r
} from "framer";
import {
    DatabaseCollection as a,
    DatabaseDictionaryIndex as s
} from "./wntZHFtmu-0.js";
import {
    resolveRichText as n
} from "./wntZHFtmu-1.js";
let i = {
        c8o1lXQcN: {
            isNullable: !0,
            type: t.ResponsiveImage
        },
        dfdXpu2Pt: {
            isNullable: !0,
            type: t.String
        },
        DXJn62ayc: {
            isNullable: !0,
            type: t.ResponsiveImage
        },
        fA4pN6bWw: {
            isNullable: !0,
            type: t.Number
        },
        hQlkx64TH: {
            isNullable: !0,
            type: t.Enum
        },
        id: {
            isNullable: !1,
            type: t.String
        },
        ljgwuKQcN: {
            isNullable: !0,
            type: t.ResponsiveImage
        },
        lRZVmSGMO: {
            isNullable: !0,
            type: t.String
        },
        nextItemId: {
            isNullable: !0,
            type: t.String
        },
        nHt8OFsOH: {
            isNullable: !0,
            type: t.Enum
        },
        PjsoUeN7M: {
            isNullable: !0,
            type: t.String
        },
        previousItemId: {
            isNullable: !0,
            type: t.String
        },
        RHTZjLu99: {
            isNullable: !0,
            type: t.String
        },
        s94B0dg4U: {
            isNullable: !0,
            type: t.Number
        },
        S9tza6guz: {
            isNullable: !0,
            type: t.Enum
        },
        sZRKrg0Hj: {
            isNullable: !0,
            type: t.String
        },
        TeXVv3jvk: {
            isNullable: !0,
            type: t.Enum
        },
        tg_0oOqEi: {
            isNullable: !0,
            type: t.RichText
        },
        TVfRT_pBM: {
            isNullable: !0,
            type: t.String
        },
        W8Cp5fqC3: {
            isNullable: !0,
            type: t.String
        },
        Xg0usEnHu: {
            isNullable: !0,
            type: t.String
        },
        ZuVZlqX0X: {
            isNullable: !0,
            type: t.String
        }
    },
    o = ["id", "tg_0oOqEi"],
    m = {
        type: 1
    },
    c = ["previousItemId", "tg_0oOqEi"],
    u = ["nextItemId", "tg_0oOqEi"],
    p = ["id", "W8Cp5fqC3"],
    d = ["W8Cp5fqC3", "id"],
    f = ["dfdXpu2Pt", "tg_0oOqEi"],
    g = {
        type: 0
    },
    w = ["W8Cp5fqC3", "tg_0oOqEi"],
    y = ["tg_0oOqEi", "tg_0oOqEi"],
    N = ["DXJn62ayc", "tg_0oOqEi"],
    h = ["c8o1lXQcN", "tg_0oOqEi"],
    S = ["ljgwuKQcN", "tg_0oOqEi"],
    H = ["fA4pN6bWw", "tg_0oOqEi"],
    R = ["s94B0dg4U", "tg_0oOqEi"],
    E = ["TeXVv3jvk", "tg_0oOqEi"],
    O = ["hQlkx64TH", "tg_0oOqEi"],
    F = ["S9tza6guz", "tg_0oOqEi"],
    x = ["nHt8OFsOH", "tg_0oOqEi"],
    Z = ["lRZVmSGMO", "tg_0oOqEi"],
    k = ["ZuVZlqX0X", "tg_0oOqEi"],
    q = ["RHTZjLu99", "tg_0oOqEi"],
    T = ["Xg0usEnHu", "tg_0oOqEi"],
    _ = ["PjsoUeN7M", "tg_0oOqEi"],
    C = ["sZRKrg0Hj", "tg_0oOqEi"],
    V = ["TVfRT_pBM", "tg_0oOqEi"],
    b = [],
    U = e => {
        let t = b[e];
        if (t) return t().then(e => e.default);
    },
    L = new r,
    B = new l(L),
    I = {
        collectionByLocaleId: {
            default: new a({
                chunks: [new URL("./wntZHFtmu-chunk-default-0.framercms",
                    import.meta.url).href.replace("/modules/", "/cms/")],
                indexes: [new s({
                    collation: m,
                    collectionSchema: i,
                    fieldNames: o,
                    range: {
                        from: 0,
                        to: 1314
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new s({
                    collation: m,
                    collectionSchema: i,
                    fieldNames: c,
                    range: {
                        from: 1314,
                        to: 2627
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new s({
                    collation: m,
                    collectionSchema: i,
                    fieldNames: u,
                    range: {
                        from: 2627,
                        to: 3936
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new s({
                    collation: m,
                    collectionSchema: i,
                    fieldNames: p,
                    range: {
                        from: 3936,
                        to: 6191
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new s({
                    collation: m,
                    collectionSchema: i,
                    fieldNames: d,
                    range: {
                        from: 6191,
                        to: 8446
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new s({
                    collation: g,
                    collectionSchema: i,
                    fieldNames: f,
                    range: {
                        from: 8446,
                        to: 10316
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new s({
                    collation: g,
                    collectionSchema: i,
                    fieldNames: w,
                    range: {
                        from: 10316,
                        to: 12182
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new s({
                    collation: g,
                    collectionSchema: i,
                    fieldNames: y,
                    range: {
                        from: 12182,
                        to: 13107
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new s({
                    collation: g,
                    collectionSchema: i,
                    fieldNames: N,
                    range: {
                        from: 13107,
                        to: 29807
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new s({
                    collation: g,
                    collectionSchema: i,
                    fieldNames: h,
                    range: {
                        from: 29807,
                        to: 42984
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new s({
                    collation: g,
                    collectionSchema: i,
                    fieldNames: S,
                    range: {
                        from: 42984,
                        to: 56157
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new s({
                    collation: g,
                    collectionSchema: i,
                    fieldNames: H,
                    range: {
                        from: 56157,
                        to: 57258
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new s({
                    collation: g,
                    collectionSchema: i,
                    fieldNames: R,
                    range: {
                        from: 57258,
                        to: 58359
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new s({
                    collation: g,
                    collectionSchema: i,
                    fieldNames: E,
                    range: {
                        from: 58359,
                        to: 59680
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new s({
                    collation: g,
                    collectionSchema: i,
                    fieldNames: O,
                    range: {
                        from: 59680,
                        to: 61001
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new s({
                    collation: g,
                    collectionSchema: i,
                    fieldNames: F,
                    range: {
                        from: 61001,
                        to: 62322
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new s({
                    collation: g,
                    collectionSchema: i,
                    fieldNames: x,
                    range: {
                        from: 62322,
                        to: 63643
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new s({
                    collation: g,
                    collectionSchema: i,
                    fieldNames: Z,
                    range: {
                        from: 63643,
                        to: 65513
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new s({
                    collation: g,
                    collectionSchema: i,
                    fieldNames: k,
                    range: {
                        from: 65513,
                        to: 89878
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new s({
                    collation: g,
                    collectionSchema: i,
                    fieldNames: q,
                    range: {
                        from: 89878,
                        to: 91126
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new s({
                    collation: g,
                    collectionSchema: i,
                    fieldNames: T,
                    range: {
                        from: 91126,
                        to: 92051
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new s({
                    collation: g,
                    collectionSchema: i,
                    fieldNames: _,
                    range: {
                        from: 92051,
                        to: 92976
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new s({
                    collation: g,
                    collectionSchema: i,
                    fieldNames: C,
                    range: {
                        from: 92976,
                        to: 96849
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new s({
                    collation: g,
                    collectionSchema: i,
                    fieldNames: V,
                    range: {
                        from: 96849,
                        to: 106282
                    },
                    url: new URL("./wntZHFtmu-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                })],
                resolveRichText: n,
                resolveVectorSetItem: U,
                schema: i
            })
        },
        displayName: "Shop"
    };
export default I;
e(I, {
    dfdXpu2Pt: {
        defaultValue: "",
        title: "Title",
        type: t.String
    },
    W8Cp5fqC3: {
        title: "Slug",
        type: t.String
    },
    tg_0oOqEi: {
        defaultValue: "",
        title: "Description",
        type: t.RichText
    },
    DXJn62ayc: {
        title: "Image 1",
        type: t.ResponsiveImage
    },
    c8o1lXQcN: {
        title: "Image 2",
        type: t.ResponsiveImage
    },
    ljgwuKQcN: {
        title: "Image 3",
        type: t.ResponsiveImage
    },
    fA4pN6bWw: {
        defaultValue: 0,
        title: "Price",
        type: t.Number
    },
    s94B0dg4U: {
        defaultValue: 0,
        title: "Compare-at Price",
        type: t.Number
    },
    TeXVv3jvk: {
        options: ["Vh9sRq_3s", "Fq_AXqo4D", "OEwDcz1dH", "tDxUvjIz9", "XNsCLcZn_"],
        optionTitles: ["None", "timeless-classics", "bridal-bliss", "minimalist-elegance", "plywood"],
        title: "Collections",
        type: t.Enum
    },
    hQlkx64TH: {
        options: ["QunpOgNIx", "PuLcUu5pK", "chwuWqQ49", "wW8k4CAo6", "ypRUWE5h8", "kaKEso4_0"],
        optionTitles: ["None", "Timeless Classics", "Bridal Bliss", "Minimalist Elegance", "plywood", "Vistiq"],
        title: "Tags",
        type: t.Enum
    },
    S9tza6guz: {
        options: ["MZaJGhmYW", "rYZzlYJVl", "ZVH8SfAfH", "covN3WkED", "tQItEhhpH", "UXJpagZJk", "yrcjHC7bO", "DPgCwEbF2", "MEgwCRWcg", "HmTlBhlkx"],
        optionTitles: ["None", "Necklaces", "Bracelets", "Earrings", "Rings", "Anklets", "Merch", "Skincare & Body Care", "Aromatherapy & Ritual Essentials", "Wellness Tools"],
        title: "Product Type",
        type: t.Enum
    },
    nHt8OFsOH: {
        options: ["zjAbN45FB", "Oq5KsJ8cA", "Te27jD1XG", "SmBPUl6gW", "du3WBHwVP", "LtV92JFiC", "vL3scWHxP", "S9NzG85_z", "bj8DzRmHn", "WJSpmz9__", "R7syyJWPS", "GIKBGVtab", "wR_jmN_s7", "yPLHIU_4D", "WNJ7uMknC", "BiBIAjFr5", "lsFyh8Nyi", "v1to2Sz_O", "EvQ3jUlcH", "G3K1e4x1g", "dVtu0JYPR", "YNFEqnwcW"],
        optionTitles: ["None", "Necklaces", "Bracelets", "Earrings", "Rings", "Anklets", "Print Books", "Flasks", "Shopping Totes", "Mugs", "Keychains", "Body Oil", "Facial Cleansers", "Lotions & Moisturizers", "Skin Care Masks & Peels", "Candles", "Air Fresheners", "Massage Oil", "Bath Additives", "Skin Care Rollers", "Eye Masks", "Massage Stones"],
        title: "Category",
        type: t.Enum
    },
    lRZVmSGMO: {
        defaultValue: "",
        title: "SEO Page Title",
        type: t.String
    },
    ZuVZlqX0X: {
        defaultValue: "",
        title: "SEO Page Description",
        type: t.String
    },
    RHTZjLu99: {
        defaultValue: "",
        title: "Vendor",
        type: t.String
    },
    Xg0usEnHu: {
        defaultValue: "",
        title: "SKU",
        type: t.String
    },
    PjsoUeN7M: {
        defaultValue: "",
        title: "Barcode",
        type: t.String
    },
    sZRKrg0Hj: {
        defaultValue: "",
        title: "Variant Options",
        type: t.String
    },
    TVfRT_pBM: {
        defaultValue: "",
        title: "Shopify Data",
        type: t.String
    },
    previousItemId: {
        dataIdentifier: "local-module:collection/wntZHFtmu:default",
        title: "Previous",
        type: t.CollectionReference
    },
    nextItemId: {
        dataIdentifier: "local-module:collection/wntZHFtmu:default",
        title: "Next",
        type: t.CollectionReference
    }
});
export const TeXVv3jvkToDisplayName = (e, t) => {
    switch (t ? .fallback, e) {
        case "Vh9sRq_3s":
            return "None";
        case "Fq_AXqo4D":
            return "timeless-classics";
        case "OEwDcz1dH":
            return "bridal-bliss";
        case "tDxUvjIz9":
            return "minimalist-elegance";
        case "XNsCLcZn_":
            return "plywood";
        default:
            return "";
    }
};
export const hQlkx64THToDisplayName = (e, t) => {
    switch (t ? .fallback, e) {
        case "QunpOgNIx":
            return "None";
        case "PuLcUu5pK":
            return "Timeless Classics";
        case "chwuWqQ49":
            return "Bridal Bliss";
        case "wW8k4CAo6":
            return "Minimalist Elegance";
        case "ypRUWE5h8":
            return "plywood";
        case "kaKEso4_0":
            return "Vistiq";
        default:
            return "";
    }
};
export const S9tza6guzToDisplayName = (e, t) => {
    switch (t ? .fallback, e) {
        case "MZaJGhmYW":
            return "None";
        case "rYZzlYJVl":
            return "Necklaces";
        case "ZVH8SfAfH":
            return "Bracelets";
        case "covN3WkED":
            return "Earrings";
        case "tQItEhhpH":
            return "Rings";
        case "UXJpagZJk":
            return "Anklets";
        case "yrcjHC7bO":
            return "Merch";
        case "DPgCwEbF2":
            return "Skincare & Body Care";
        case "MEgwCRWcg":
            return "Aromatherapy & Ritual Essentials";
        case "HmTlBhlkx":
            return "Wellness Tools";
        default:
            return "";
    }
};
export const nHt8OFsOHToDisplayName = (e, t) => {
    switch (t ? .fallback, e) {
        case "zjAbN45FB":
            return "None";
        case "Oq5KsJ8cA":
            return "Necklaces";
        case "Te27jD1XG":
            return "Bracelets";
        case "SmBPUl6gW":
            return "Earrings";
        case "du3WBHwVP":
            return "Rings";
        case "LtV92JFiC":
            return "Anklets";
        case "vL3scWHxP":
            return "Print Books";
        case "S9NzG85_z":
            return "Flasks";
        case "bj8DzRmHn":
            return "Shopping Totes";
        case "WJSpmz9__":
            return "Mugs";
        case "R7syyJWPS":
            return "Keychains";
        case "GIKBGVtab":
            return "Body Oil";
        case "wR_jmN_s7":
            return "Facial Cleansers";
        case "yPLHIU_4D":
            return "Lotions & Moisturizers";
        case "WNJ7uMknC":
            return "Skin Care Masks & Peels";
        case "BiBIAjFr5":
            return "Candles";
        case "lsFyh8Nyi":
            return "Air Fresheners";
        case "v1to2Sz_O":
            return "Massage Oil";
        case "EvQ3jUlcH":
            return "Bath Additives";
        case "G3K1e4x1g":
            return "Skin Care Rollers";
        case "dVtu0JYPR":
            return "Eye Masks";
        case "YNFEqnwcW":
            return "Massage Stones";
        default:
            return "";
    }
};
export const enumToDisplayNameFunctions = {
    hQlkx64TH: hQlkx64THToDisplayName,
    nHt8OFsOH: nHt8OFsOHToDisplayName,
    S9tza6guz: S9tza6guzToDisplayName,
    TeXVv3jvk: TeXVv3jvkToDisplayName
};
export const utils = {
    async getSlugByRecordId(e, t) {
        let [l] = await B.get({
            from: {
                data: I,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "W8Cp5fqC3",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "id",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, t).readAsync();
        return l ? .W8Cp5fqC3;
    },
    async getRecordIdBySlug(e, t) {
        let [l] = await B.get({
            from: {
                data: I,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "id",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "W8Cp5fqC3",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, t).readAsync();
        return l ? .id;
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "utils": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "data",
            "name": "data",
            "annotations": {
                "framerData": "",
                "framerAutoSizeImages": "true",
                "framerCollectionUtils": "1",
                "framerColorSyntax": "false",
                "framerEnumToDisplayNameUtils": "2",
                "framerCollectionId": "wntZHFtmu",
                "framerRecordIdKey": "id",
                "framerContractVersion": "1",
                "framerSlug": "W8Cp5fqC3"
            }
        },
        "enumToDisplayNameFunctions": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "nHt8OFsOHToDisplayName": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "hQlkx64THToDisplayName": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "TeXVv3jvkToDisplayName": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "S9tza6guzToDisplayName": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}