// Generated by Framer (b4533c2)
import {
    addPropertyControls as e,
    ControlType as t,
    QueryCache as i,
    QueryEngine as l
} from "framer";
import {
    DatabaseCollection as r
} from "./xqQPQSXue-0.js";
import {
    resolveRichText as a
} from "./xqQPQSXue-1.js";
import {
    resolveRichTextSk as n
} from "./xqQPQSXue-3.js";
let o = {
        cNPiWof_F: {
            isNullable: !0,
            type: t.RichText
        },
        EhDbBA2iQ: {
            isNullable: !0,
            type: t.Link
        },
        EO0x5ti8F: {
            isNullable: !0,
            type: t.String
        },
        id: {
            isNullable: !1,
            type: t.String
        },
        ipL9QRPNl: {
            isNullable: !0,
            type: t.ResponsiveImage
        },
        nextItemId: {
            isNullable: !0,
            type: t.String
        },
        previousItemId: {
            isNullable: !0,
            type: t.String
        },
        SbRE1E_XB: {
            isNullable: !0,
            type: t.String
        }
    },
    u = [],
    p = e => {
        let t = u[e];
        if (t) return t().then(e => e.default);
    },
    s = new l,
    c = new i(s),
    m = {
        collectionByLocaleId: {
            default: new r({
                chunks: [new URL("./xqQPQSXue-chunk-default-0.framercms",
                    import.meta.url).href.replace("/modules/", "/cms/")],
                indexes: [],
                resolveRichText: a,
                resolveVectorSetItem: p,
                schema: o
            }),
            GowRT4MZZ: new r({
                chunks: [new URL("./xqQPQSXue-chunk-GowRT4MZZ-0.framercms",
                    import.meta.url).href.replace("/modules/", "/cms/")],
                indexes: [],
                resolveRichText: n,
                resolveVectorSetItem: p,
                schema: o
            })
        },
        displayName: "Services Categories"
    };
export default m;
e(m, {
    SbRE1E_XB: {
        defaultValue: "",
        title: "Title",
        type: t.String
    },
    EO0x5ti8F: {
        title: "Slug",
        type: t.String
    },
    ipL9QRPNl: {
        title: "Image",
        type: t.ResponsiveImage
    },
    EhDbBA2iQ: {
        title: "Link",
        type: t.Link
    },
    cNPiWof_F: {
        defaultValue: "",
        title: "Short Description",
        type: t.RichText
    },
    previousItemId: {
        dataIdentifier: "local-module:collection/xqQPQSXue:default",
        title: "Previous",
        type: t.CollectionReference
    },
    nextItemId: {
        dataIdentifier: "local-module:collection/xqQPQSXue:default",
        title: "Next",
        type: t.CollectionReference
    }
});
export const enumToDisplayNameFunctions = {};
export const utils = {
    async getSlugByRecordId(e, t) {
        let [i] = await c.get({
            from: {
                data: m,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "EO0x5ti8F",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "id",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, t).readAsync();
        return i ? .EO0x5ti8F;
    },
    async getRecordIdBySlug(e, t) {
        let [i] = await c.get({
            from: {
                data: m,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "id",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "EO0x5ti8F",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, t).readAsync();
        return i ? .id;
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "utils": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "data",
            "name": "data",
            "annotations": {
                "framerContractVersion": "1",
                "framerEnumToDisplayNameUtils": "2",
                "framerSlug": "EO0x5ti8F",
                "framerCollectionId": "xqQPQSXue",
                "framerCollectionUtils": "1",
                "framerData": "",
                "framerAutoSizeImages": "true",
                "framerColorSyntax": "false",
                "framerRecordIdKey": "id"
            }
        },
        "enumToDisplayNameFunctions": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}