// Generated by Framer (0c5492c)
import {
    fontStore
} from "framer";
fontStore.loadFonts(["GF;Kumbh Sans-regular", "GF;Kumbh Sans-700"]);
export const fonts = [{
    explicitInter: true,
    fonts: [{
        family: "Kumbh Sans",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/kumbhsans/v22/c4mP1n92AsfhuCq6tVsaoIx1LQICk0boNoq0SjlDfnzKo-bF3mdQkZYA9LTuUkqaLg.woff2",
        weight: "400"
    }, {
        family: "Kumbh Sans",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/kumbhsans/v22/c4mP1n92AsfhuCq6tVsaoIx1LQICk0boNoq0SjlDfnzKo-bF3mdQdpEA9LTuUkqaLg.woff2",
        weight: "700"
    }]
}];
export const css = ['.framer-a9HBU .framer-styles-preset-14yk1za:not(.rich-text-wrapper), .framer-a9HBU .framer-styles-preset-14yk1za.rich-text-wrapper p { --framer-font-family: "Kumbh Sans", "Kumbh Sans Placeholder", sans-serif; --framer-font-family-bold: "Kumbh Sans", "Kumbh Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 12px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-9ac73791-4104-4253-8947-ec829a0f0956, #666666); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: inherit; }'];
export const className = "framer-a9HBU";
export const __FramerMetadata__ = {
    "exports": {
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}