// Generated by Framer (9e04080)

import siteMetadata from "../siteMetadata/siteMetadata";

const toString = (value) => {
    return typeof value === "string" ? value : String(value);
};


export default function metadata(params, activeLocale) {
const eqn80UisM = params?.eqn80UisM
return {breakpoints: [{hash: "1mm140p", mediaQuery: "(min-width: 1200px)"}, {hash: "qzx9nt", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "1dcnge2", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-Hsi0e", title: `${eqn80UisM !== undefined ? toString(eqn80UisM) : "{{eqn80UisM}}"} - Vistiq`, viewport: "width=device-width"}
}

export const metadataVersion = 1