// Generated by Framer (9e04080)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "no4g6a", mediaQuery: "(min-width: 1200px)"}, {hash: "1yyf15p", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "rakiui", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-QrDSq", title: siteMetadata(params, activeLocale).title || "Shop", viewport: "width=device-width"}
}

export const metadataVersion = 1